// Shared Aluma-branded styles for all auth emails (Hebrew, RTL)
export const BRAND = {
  name: 'Aluma',
  primary: '#B87258',
  foreground: '#4A2617',
  muted: '#7A5B4E',
  cream: '#F3EDE4',
  border: '#E6DCCF',
}

export const styles = {
  main: {
    backgroundColor: '#ffffff',
    fontFamily: '"Assistant", "Segoe UI", Arial, sans-serif',
    margin: 0,
    padding: '32px 12px',
  } as const,
  container: {
    maxWidth: '520px',
    margin: '0 auto',
    backgroundColor: '#ffffff',
    border: `1px solid ${BRAND.border}`,
    borderRadius: '4px',
    padding: '0',
  } as const,
  header: {
    backgroundColor: BRAND.cream,
    padding: '28px 32px',
    textAlign: 'center' as const,
    borderBottom: `1px solid ${BRAND.border}`,
  } as const,
  brand: {
    fontSize: '26px',
    letterSpacing: '6px',
    color: BRAND.foreground,
    margin: 0,
    fontWeight: 300 as const,
  } as const,
  tagline: {
    fontSize: '11px',
    letterSpacing: '3px',
    color: BRAND.muted,
    margin: '8px 0 0',
    textTransform: 'uppercase' as const,
  } as const,
  body: { padding: '32px 32px 28px', direction: 'rtl' as const, textAlign: 'right' as const },
  h1: {
    fontSize: '22px',
    fontWeight: 600 as const,
    color: BRAND.foreground,
    margin: '0 0 18px',
  } as const,
  text: {
    fontSize: '15px',
    color: BRAND.foreground,
    lineHeight: '1.7',
    margin: '0 0 20px',
  } as const,
  buttonWrap: { textAlign: 'center' as const, margin: '28px 0' } as const,
  button: {
    backgroundColor: BRAND.primary,
    color: '#ffffff',
    fontSize: '14px',
    letterSpacing: '2px',
    borderRadius: '2px',
    padding: '14px 32px',
    textDecoration: 'none',
    display: 'inline-block',
    textTransform: 'uppercase' as const,
  } as const,
  code: {
    fontSize: '28px',
    letterSpacing: '10px',
    color: BRAND.foreground,
    textAlign: 'center' as const,
    backgroundColor: BRAND.cream,
    padding: '18px',
    borderRadius: '4px',
    margin: '20px 0',
    fontWeight: 600 as const,
  } as const,
  footer: {
    fontSize: '12px',
    color: BRAND.muted,
    lineHeight: '1.6',
    margin: '24px 0 0',
    paddingTop: '20px',
    borderTop: `1px solid ${BRAND.border}`,
  } as const,
  outerFooter: {
    textAlign: 'center' as const,
    fontSize: '11px',
    color: BRAND.muted,
    margin: '20px auto 0',
    maxWidth: '520px',
    lineHeight: '1.6',
  } as const,
}
